# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170324_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='related_to',
            new_name='followers',
        ),
    ]
