# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=15)),
                ('poster_path', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(related_name='movies', to='movies.Category')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
    ]
