# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id'], 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category_ids',
            new_name='categories',
        ),
    ]
