# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
